### ISSUE TITLE
Fatal Error during 900 job

### ISSUE THREAD

**Issue by atomaka** [lansingcodes/lubot#20]
I haven't looked at it, but our 900 fails sometimes with the following error:

```
lubot_1    | [Fri Aug 26 2016 09:00:00 GMT-0400 (EDT)] ERROR RangeError: Length extends beyond buffer
lubot_1    |   at RangeError (native)
lubot_1    |   at Object.fs.readSync (fs.js:731:19)
lubot_1    |   at tryReadSync (fs.js:486:20)
lubot_1    |   at Object.fs.readFileSync (fs.js:526:19)
lubot_1    |   at Object.require.extensions..ls (/opt/hubot/node_modules/livescript/lib/node.js:40:15)
lubot_1    |   at Module.load (/opt/hubot/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
lubot_1    |   at tryModuleLoad (module.js:417:12)
lubot_1    |   at Function.Module._load (module.js:409:3)
lubot_1    |   at Module.require (module.js:468:17)
lubot_1    |   at require (internal/module.js:20:19)
lubot_1    |   at Object.<anonymous> (/opt/hubot/lib/scheduled-tasks/check-for-upcoming-events.ls:4:18)
lubot_1    | 1| // Generated by LiveScript 1.5.0
lubot_1    | 2| var moment, chooseBeverage, generateWelcomeEmailFor, UpcomingEventsFetcher, EventsCacher, announcementRoom, announcementRoomFor, isToday, isInTwoDays, isInAWeek, formatTimeOnly;
lubot_1    | 3| moment = require('moment');
lubot_1    | 4+ chooseBeverage = require('../helpers/choose-beverage');
lubot_1    | 5| generateWelcomeEmailFor = require('../helpers/generate-welcome-email-for');
lubot_1    | 6| UpcomingEventsFetcher = require('../fetchers/upcoming-events-fetcher');
lubot_1    | 7| EventsCacher = require('../cachers/events-cacher');
lubot_1    | 8| announcementRoom = 'general';
lubot_1    |   at Module._compile (module.js:541:32)
lubot_1    |   at Object.require.extensions..ls (/opt/hubot/node_modules/livescript/lib/node.js:52:21)
lubot_1    |   at Module.load (/opt/hubot/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
lubot_1    |   at tryModuleLoad (module.js:417:12)
lubot_1    |   at Function.Module._load (module.js:409:3)
lubot_1    |   at Module.require (module.js:468:17)
lubot_1    |   at require (internal/module.js:20:19)
lubot_1    |   at CronJob.runModule (/opt/hubot/lib/initializers/scheduler.ls:9:7)
lubot_1    |   at CronJob.fireOnTick (/opt/hubot/node_modules/cron/lib/cron.js:392:22)
lubot_1    |   at Timeout.callbackWrapper [as _onTimeout] (/opt/hubot/node_modules/cron/lib/cron.js:435:9)
lubot_1    |   at tryOnTimeout (timers.js:228:11)
lubot_1    |   at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by atomaka** [comment]
Didn't fire again today. I'm not sure why as the error occurred much earlier:

```
lubot_1    | [Thu Sep 01 2016 08:46:00 GMT-0400 (EDT)] ERROR RangeError: out of range index
lubot_1    |   at RangeError (native)
lubot_1    |   at fastCopy (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:323:24)
lubot_1    |   at Receiver.add (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:84:3)
lubot_1    |   at TLSSocket.firstHandler (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
lubot_1    |   at emitOne (events.js:96:13)
lubot_1    |   at TLSSocket.emit (events.js:188:7)
lubot_1    |   at readableAddChunk (_stream_readable.js:177:18)
lubot_1    |   at TLSSocket.Readable.push (_stream_readable.js:135:10)
lubot_1    |   at TLSWrap.onread (net.js:542:20)
lubot_1    |
lubot_1    | [Thu Sep 01 2016 08:46:00 GMT-0400 (EDT)] ERROR RangeError: out of range index
lubot_1    | RangeError: out of range index
lubot_1    |   at RangeError (native)
lubot_1    |   at fastCopy (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:323:24)
lubot_1    |   at Receiver.add (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:84:3)
lubot_1    |   at TLSSocket.firstHandler (/opt/hubot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
lubot_1    |   at emitOne (events.js:96:13)
lubot_1    |   at TLSSocket.emit (events.js:188:7)
lubot_1    |   at readableAddChunk (_stream_readable.js:177:18)
lubot_1    |   at TLSSocket.Readable.push (_stream_readable.js:135:10)
lubot_1    |   at TLSWrap.onread (net.js:542:20)
lubot_1    |
lubot_1    | [Thu Sep 01 2016 08:46:03 GMT-0400 (EDT)] INFO Connecting...
lubot_1    | [Thu Sep 01 2016 08:46:03 GMT-0400 (EDT)] INFO Logged in as lubot of Lansing Codes, but not yet connected
lubot_1    | [Thu Sep 01 2016 08:46:03 GMT-0400 (EDT)] INFO Slack client now connected
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/lib/initializers/email-responder.ls is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/lib/initializers/events-responder.ls is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/lib/initializers/fuck-shit-up.ls is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/lib/initializers/http-status-code-lookup.ls is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/lib/initializers/mentioned-rooms-referencer.ls is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/lib/initializers/new-participant-notifier.ls is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/lib/initializers/scheduler.ls is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/lib/initializers/troubleshooter.ls is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/lib/initializers/tweeter.ls is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/lib/initializers/watch-for-disconnected.ls is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO /opt/hubot/scripts/initialize.coffee is using deprecated documentation syntax
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.
lubot_1    |
lubot_1    | Your hubot-scripts.json is empty, so you just need to remove it.
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO hubot-redis-brain: Discovered redis from REDIS_URL environment variable
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO hubot-redis-brain: Successfully authenticated to Redis
lubot_1    | [Thu Sep 01 2016 08:46:04 GMT-0400 (EDT)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
```

**Comment by egillespie** [comment]
The event data is now limited in length within Firebase. I'm optimistic that this issue won't happen any more.
